config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :rooms do
    resources :reservations, only: [ :show, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations
  validates :city, presence: true
  validates :name, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms
  has_many :reservations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def create
    @room = Room.find(params[:room_id])
    @reservation = Reservation.new(resa_params)
    @reservation.room = @room
    @reservation.user = current_user
    if @reservation.save
      redirect_to room_reservation_path(@room, @reservation)
    else
      render :new
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
    @room = Room.find(params[:room_id])
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to rooth_path(@reservation.room)
  end

  private

  def resa_params
    params.require(:reservation).permit(:description, :date)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    if params[:query].present?
      @rooms = Room.where("city ILIKE ?", "%#{params[:query]}%")
    else
      @rooms = Room.all
     @markers = @rooms.geocoded.map do |room|
      {
        lat: room.latitude,
        lng: room.longitude
      }
    end
    end
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
    @marker = { lat: @room.latitude, lng: @room.longitude, image_url: helpers.asset_url('guitare.jpg') }
  end

  def new
    @room = Room.new
  end

  private

  def room_params
    params.require(:room).permit(:name, :city)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1471614654469-512ee6a4397a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80);">
    <div class="container text-center">
      <h1><strong>Music-me</strong></h1>
      <p>Rechercher, Reserver, Jouer </p>
    </div>
  </div>
    <% if action_name != "/rooms/new" %>
      <%= render 'shared/navbar' %>
    <% end %>
    <%= yield %>
    <%= render 'shared/flashes' %>
   <!-- Footer -->
  <footer class="page-footer font-small cyan darken-3">

  <!-- Footer Elements -->
  <div class="container text-center">

    <!-- Grid row-->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-12 py-5">
        <div class="mb-5 flex-center">

          <!-- Facebook -->
          <a class="fb-ic">
            <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic">
            <i class="fab fa-google-plus-g fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic">
            <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Pinterest-->
          <a class="pin-ic">
            <i class="fab fa-pinterest fa-lg white-text fa-2x"> </i>
          </a>
        </div style="color:#333333" >
         by team MVC©
      </div>
      <!-- Grid column -->
    </div>
    <!-- Grid row-->
  </div>
  <!-- Footer Elements -->
  <!-- Copyright -->
  <!-- Copyright -->
</footer>
<!-- Footer -->
<script src='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css' rel='stylesheet' />
</body>
</html>

app/views/reservations/show.html.erb
<div class="container p-5">

<div class="text-center">

  <div class="col-12">
    <h1>Reservation</h1>
    <h5>Merci pour votre réservation au <%= @room.name %> à <%= @room.city %></h5>
    <h6>Date: <%= @reservation.date %></h6>

    </br>
    <%= link_to "Back", root_path %>
  </div>
</div>

</div>

app/views/rooms/_info_window.html.erb
<h2><%= room.name %></h2>
<p><%= room.address %></p>

app/views/rooms/index.html.erb
  <div class="row justify-content-center" class="containerroom">
  <h1 class="text-center"> Vos Music Rooms près de chez vous </h1>
</div>
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-8 mt-5">
            <% @rooms.each do |room| %>
            <div class="card">
                <div class="card-horizontal d-flex">
                    <div class="img-square-wrapper">
                        <img class="" src="<%=room.photo%>" alt="Card image cap" width="300" height="180">
                    </div>
                    <div class="card-body ">
                        <h4 class="card-title"><%= link_to room.name, room_path(room)  %></h4>


                        <p class="card-text"><%= room.description %></p>
                        <p class="card-text"><%= link_to "Plus d'infos ...", room_path(room) %></p>
                    </div>
                </div>
                <div class="card-footer">
                    <p class="text-muted"><%=room.address %></p>
                </div>
            </div>
            <%end%>
        </div>
    </div>
</div>
<br>

app/views/rooms/new.html.erb
new.html.erb

app/views/rooms/show.html.erb
<div class="containershow">
  <div class="containerroom">
  <h1> <%= @room.name %> </h1>
  <h3> <%= @room.city %> </h3>
  <h6> <%= @room.address %> </h6>

</div>

  <br><br><br>
  <div class="row pb-5">
    <div class="col-lg-6">
     Notre Home Studio réunit les meilleures conditions propices au travail en Studio d'enregistrement.
     Depuis de nombreuses années nous efforçons de nous mettre au service de votre projet !
     Venez enregistrer ou simplement répéter vos morceaux dans notre espace dédié.
     Have fun!
     <br>
     C’est un endroit indispensable à la production musicale de qualité car il met à la disposition des artistes, réalisateurs et ingénieurs un personnel qualifié et compétent, un parc matériel haut de gamme et des espaces de travail dont l’acoustique est étudiée et maitrisée.
      <br>Le studio est l’endroit où sont réunis le maximum de compétences humaines, les outils indispensables et les espaces insonorisés adéquats. Enregistrer un instrument dans un lieu spécifique est le gage de la qualité sonore, utiliser un piano à queue ou une batterie ne peut être fait n’importe où.
      <br>La musique demande beaucoup de compétence différentes, arrangeur, réalisateur, ingénieur du son, mixeur, mastering, chacun est spécialisé dans son travail pour donner le meilleur au projet.
    </div>
    <div class="col-lg-6">
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-100" src="https://trempo.com/wp-content/uploads/2019/08/studio11_davidgallard_clack-2000x1333.jpg" alt="First slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="https://www.zikinf.com/_gfx/annonces/dyn/studio-d-enregistrement-2614650.jpg?1558540637" alt="Second slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="https://www.montmartrerecording.com/wp-content/uploads/2015/04/cabine-enregistrement-record-paris.jpg" alt="Third slide">
        </div>
          </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
    </div>
    <div class="row p-5">
    <div class="col-lg-6">

      <div class="form-wrapper" id="calendar">
      <%= simple_form_for [@room, @reservation] do |f| %>
        <%= f.input :date, as: :string, input_html: { class: "datepicker" }, placeholder: "Choisissez votre date de réservation" %>
        <%= f.button :submit, "Réserver", class: "btni" %>
      <% end %>
      </div>
      </div>

      <div class="col-lg-6">
      <div id="map"
        style="width: 800px; height: 300px;"
        data-marker="<%= @marker.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
      </div>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar-fixed-top scrolled">
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a <%= link_to "Home", root_path, class: "btn btn-secondary text-decoration-none"  %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <div class="form-inline" id="search">
   <%= form_tag rooms_path, method: :get do %>
      <%= text_field_tag :query,
    params[:query],
    class: "form-control form-control-sm ml-3 btn btn-outline-dark",
    style: "width: 300px",
    placeholder: "   🤘🏽 Entrer votre ville 🤘🏽   "
    %>
  <% end %>
  </div>
</div>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      </li>
      <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Profil</a>
          <a class="dropdown-item" href="#">Log Out</a>
        </div>
      </li>
    </ul>
  </div>
</div>
</nav>